Methods

In [ ]:
class Student:
  collage_name=('abe collage ')
  name="anoniymous"#class attribute
  def __init__(self,name,marks):# self and any argument can pass..
    self.name=name# object attribute,....(obj attribute > class attribute)
    self.marks=marks
  def hello(self):
    print('hello')
  def get_marks(self):
    return self.get_marks
s1=Student('karan',45)
print(s1.name,s1.marks)
s2=Student('rohan',66)
print(s2.name,s2.marks)
print(s2.collage_name)
Student.collage_name
s1.hello()
print(s1.get_marks())

karan 45
rohan 66
abe collage
hello
<bound method Student.get_marks of <__main__.Student object at 0x7f16f02770a0>>

In [ ]:
class Student:
  collage_name=('abe collage ')
  name="anoniymous"#class attribute
  def __init__(self,name,marks):# self and any argument can pass..
    self.name=name# object attribute,....(obj attribute > class attribute)
    self.marks=marks
    print('adding new students in datasets')
s1=Student('karan',45)
print(s1.name,s1.marks)
s2=Student('rohan',66)
print(s2.name,s2.marks)
print(s2.collage_name)
Student.collage_name

adding new students in datasets
karan 45
adding new students in datasets
rohan 66
abe collage

'abe collage '

In [ ]:
# prompt: Lets practice

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def introduce(self):
    print(f"Hello, my name is {self.name} and I am {self.age} years old.")

person1 = Person("Alice", 30)
person1.introduce()

Hello, my name is Alice and I am 30 years old.

In [ ]:
class Student:
    def __init__(self,name,marks):
      self.name=name
      self.marks=marks
    def get_avg(self):
      sum=0
      for i in self.marks:
        sum+=i
      print(f'hi{self.name} your score is:',sum/len(self.marks))
s1=Student('Amimul',[98,79,89])
s1.get_avg()
s1.name='iranman'
s1.get_avg()

hiAmimul your score is: 88.66666666666667
hiiranman your score is: 88.66666666666667

In [ ]:
#static method|

In [ ]:
class Student:
    def __init__(self,name,marks):
      self.name=name
      self.marks=marks

    def get_avg(self):
      sum=0
      for i in self.marks:
        sum+=i
      print(f'hi{self.name} your score is:',sum/len(self.marks))
s1=Student('Amimul',[98,79,89])
s1.get_avg()
s1.name='iranman'
s1.get_avg()

hiAmimul your score is: 88.66666666666667
hiiranman your score is: 88.66666666666667

In [2]:
class Account:
  def __init__(self,bal,acc):
    self.balance=bal
    self.account_no=acc
  def debit(self,amount):
    self.balance -= amount
    print(f"Taka {amount} was debited from account")
    print('total balance = ',self.get_balance())
  def credit(self,amount):
    self.balance += amount
    print(f' taka {amount} was credited to account')
    print('total balance = ',self.get_balance())
  def get_balance(self):
    return self.balance
acc1=Account(10000,678900)
acc1.debit(1000)
acc1.credit(2000)

Taka 1000 was debited from account
total balance =  9000
 taka 2000 was credited to account
total balance =  11000